/* ==========================================================================
   SMART FOX SOLUTIONS - BONUSES SYSTEM
   Date: 2026-02-07
   Description: Add performance bonuses with manual and automatic calculation
   ========================================================================== */

-- ============================================================================
-- 1. PERFORMANCE BONUSES TABLE
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.performance_bonuses (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid REFERENCES auth.users ON DELETE CASCADE NOT NULL,
    amount numeric NOT NULL,
    bonus_type text CHECK (bonus_type IN ('manual', 'performance', 'attendance', 'punctuality', 'schedule_compliance')) DEFAULT 'manual',
    percentage numeric,
    description text,
    start_date date NOT NULL,
    end_date date,
    status text CHECK (status IN ('active', 'expired', 'rolled_back')) DEFAULT 'active',
    created_by uuid REFERENCES auth.users NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);

ALTER TABLE public.performance_bonuses ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "performance_bonuses_read_policy" ON public.performance_bonuses;
DROP POLICY IF EXISTS "performance_bonuses_insert_policy" ON public.performance_bonuses;
DROP POLICY IF EXISTS "performance_bonuses_update_policy" ON public.performance_bonuses;

CREATE POLICY "performance_bonuses_read_policy" ON public.performance_bonuses
FOR SELECT USING (
  auth.uid() = user_id OR public.check_is_admin()
);

CREATE POLICY "performance_bonuses_insert_policy" ON public.performance_bonuses
FOR INSERT WITH CHECK (public.check_is_admin());

CREATE POLICY "performance_bonuses_update_policy" ON public.performance_bonuses
FOR UPDATE USING (public.check_is_admin());

CREATE INDEX IF NOT EXISTS idx_performance_bonuses_user_id ON public.performance_bonuses(user_id);
CREATE INDEX IF NOT EXISTS idx_performance_bonuses_start_date ON public.performance_bonuses(start_date);
CREATE INDEX IF NOT EXISTS idx_performance_bonuses_status ON public.performance_bonuses(status);
CREATE INDEX IF NOT EXISTS idx_performance_bonuses_user_active ON public.performance_bonuses(user_id, status, start_date);

DROP TRIGGER IF EXISTS update_updated_at_performance_bonuses ON public.performance_bonuses;
CREATE TRIGGER update_updated_at_performance_bonuses BEFORE UPDATE ON public.performance_bonuses
FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();

-- ============================================================================
-- 2. PERFORMANCE METRICS TABLE (Asistencia, Puntualidad, Cumplimiento)
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.performance_metrics (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid REFERENCES auth.users ON DELETE CASCADE NOT NULL,
    period_start date NOT NULL,
    period_end date NOT NULL,
    attendance_score numeric DEFAULT 0,
    punctuality_score numeric DEFAULT 0,
    schedule_compliance_score numeric DEFAULT 0,
    overall_score numeric DEFAULT 0,
    calculated_at timestamp with time zone DEFAULT now(),
    UNIQUE(user_id, period_start, period_end)
);

ALTER TABLE public.performance_metrics ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "performance_metrics_read_policy" ON public.performance_metrics;
DROP POLICY IF EXISTS "performance_metrics_insert_policy" ON public.performance_metrics;

CREATE POLICY "performance_metrics_read_policy" ON public.performance_metrics
FOR SELECT USING (
  auth.uid() = user_id OR public.check_is_admin()
);

CREATE POLICY "performance_metrics_insert_policy" ON public.performance_metrics
FOR INSERT WITH CHECK (public.check_is_admin());

CREATE INDEX IF NOT EXISTS idx_performance_metrics_user_id ON public.performance_metrics(user_id);
CREATE INDEX IF NOT EXISTS idx_performance_metrics_period ON public.performance_metrics(user_id, period_start, period_end);

-- ============================================================================
-- 3. BONUS HISTORY TABLE (Para auditoría)
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.bonus_audit (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    employee_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    bonus_id bigint REFERENCES public.performance_bonuses ON DELETE SET NULL,
    previous_amount DECIMAL(12, 2),
    new_amount DECIMAL(12, 2) NOT NULL,
    change_reason TEXT,
    changed_by_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_bonus_audit_employee ON public.bonus_audit(employee_id);
CREATE INDEX IF NOT EXISTS idx_bonus_audit_changed_by ON public.bonus_audit(changed_by_id);
CREATE INDEX IF NOT EXISTS idx_bonus_audit_created_at ON public.bonus_audit(created_at DESC);

ALTER TABLE public.bonus_audit ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "bonus_audit_read_policy" ON public.bonus_audit;
DROP POLICY IF EXISTS "bonus_audit_insert_policy" ON public.bonus_audit;

CREATE POLICY "bonus_audit_read_policy" ON public.bonus_audit
FOR SELECT USING (public.check_is_admin());

CREATE POLICY "bonus_audit_insert_policy" ON public.bonus_audit
FOR INSERT WITH CHECK (public.check_is_admin());

-- ============================================================================
-- 4. HELPER FUNCTION: Calculate Performance Bonuses
-- ============================================================================

CREATE OR REPLACE FUNCTION public.calculate_bonus_for_period(
  p_user_id uuid,
  p_period_start date,
  p_period_end date
)
RETURNS NUMERIC AS $$
DECLARE
  v_total_bonus NUMERIC := 0;
  v_bonus_record RECORD;
BEGIN
  -- Sum all active bonuses for the period
  SELECT COALESCE(SUM(amount), 0)
  INTO v_total_bonus
  FROM public.performance_bonuses
  WHERE user_id = p_user_id
  AND status = 'active'
  AND start_date <= p_period_end
  AND (end_date IS NULL OR end_date >= p_period_start);

  RETURN v_total_bonus;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

-- ============================================================================
-- 5. FUNCTION: Get Total Salary with Bonuses (6 months average)
-- ============================================================================

CREATE OR REPLACE FUNCTION public.calculate_avg_salary_with_bonuses(
  p_user_id uuid,
  p_months integer DEFAULT 6
)
RETURNS NUMERIC AS $$
DECLARE
  v_start_date date;
  v_end_date date;
  v_avg_salary NUMERIC;
  v_total_with_bonuses NUMERIC;
BEGIN
  v_end_date := CURRENT_DATE;
  v_start_date := CURRENT_DATE - INTERVAL '1 month' * p_months;

  -- Get average salary from salary_audit
  SELECT COALESCE(AVG(new_salary), 0)
  INTO v_avg_salary
  FROM public.salary_audit
  WHERE employee_id = p_user_id
  AND created_at >= v_start_date::timestamp
  AND created_at <= v_end_date::timestamp;

  -- Get average bonuses for same period
  SELECT COALESCE(SUM(amount) / p_months, 0)
  INTO v_total_with_bonuses
  FROM public.performance_bonuses
  WHERE user_id = p_user_id
  AND status = 'active'
  AND start_date >= v_start_date
  AND start_date <= v_end_date;

  RETURN v_avg_salary + v_total_with_bonuses;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

-- ============================================================================
-- SCHEMA COMPLETE
-- ============================================================================
