drop extension if exists "pg_net";

alter table "public"."payroll_runs" drop constraint "unique_payroll_period";

alter table "public"."attendance_logs" drop constraint "attendance_logs_user_id_fkey";

alter table "public"."hr_requests" drop constraint "hr_requests_type_check";

alter table "public"."hr_requests" drop constraint "hr_requests_user_id_fkey";

alter table "public"."payroll_items" drop constraint "payroll_items_user_id_fkey";

alter table "public"."schedules" drop constraint "schedules_user_id_fkey";

drop index if exists "public"."unique_payroll_period";


  create table "public"."categories" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "icon" text,
    "created_at" timestamp with time zone not null default timezone('utc'::text, now())
      );


alter table "public"."categories" enable row level security;


  create table "public"."disciplinary_actions" (
    "id" bigint generated by default as identity not null,
    "user_id" uuid not null,
    "created_by" uuid not null,
    "type" text not null,
    "description" text,
    "expires_at" timestamp with time zone default (now() + '3 mons'::interval),
    "has_hearing" boolean default false,
    "hearing_date" timestamp with time zone,
    "created_at" timestamp with time zone default now()
      );


alter table "public"."disciplinary_actions" enable row level security;


  create table "public"."meetings" (
    "id" bigint generated by default as identity not null,
    "title" text not null,
    "description" text,
    "start_time" timestamp with time zone not null,
    "location_link" text,
    "is_mandatory" boolean default false,
    "created_by" uuid not null,
    "attendees" uuid[] default '{}'::uuid[],
    "created_at" timestamp with time zone default now()
      );


alter table "public"."meetings" enable row level security;


  create table "public"."order_items" (
    "id" bigint generated by default as identity not null,
    "order_id" bigint,
    "product_id" bigint,
    "quantity" integer not null,
    "unit_price" numeric(10,2) not null,
    "subtotal" numeric(10,2) not null
      );



  create table "public"."orders" (
    "id" bigint generated by default as identity not null,
    "total" numeric(10,2) not null,
    "tax" numeric(10,2) default 0,
    "status" text default 'completed'::text,
    "created_at" timestamp with time zone not null default timezone('utc'::text, now())
      );



  create table "public"."products" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "price" numeric(10,2) not null,
    "stock" integer default 0,
    "category_id" bigint,
    "image_url" text,
    "is_active" boolean default true,
    "created_at" timestamp with time zone not null default timezone('utc'::text, now())
      );


alter table "public"."products" enable row level security;

alter table "public"."hr_requests" alter column "type" drop default;

alter table "public"."payroll_items" drop column "updated_at";

alter table "public"."payroll_items" alter column "payroll_run_id" drop not null;

alter table "public"."payroll_runs" drop column "updated_at";

alter table "public"."profiles" add column "academic_data" jsonb default '{"certs": [], "education": [], "experience": []}'::jsonb;

alter table "public"."profiles" alter column "medical_data" set default '{"arl": "", "eps": "", "allergies": [], "blood_type": "", "conditions": [], "emergency_contacts": []}'::jsonb;

alter table "public"."profiles" alter column "personal_data" set default '{"ssn": "", "dependents": []}'::jsonb;

alter table "public"."profiles" alter column "sizes_data" set default '{"pants": "", "shirt": "", "shoes": "", "gloves": ""}'::jsonb;

alter table "public"."schedules" drop column "end_time";

alter table "public"."schedules" drop column "start_time";

alter table "public"."schedules" drop column "updated_at";

alter table "public"."schedules" add column "cargo" text;

alter table "public"."schedules" add column "shift_end" timestamp with time zone not null;

alter table "public"."schedules" add column "shift_start" timestamp with time zone not null;

alter table "public"."schedules" alter column "scheduled_date" set default CURRENT_DATE;

alter table "public"."schedules" alter column "scheduled_date" drop not null;

CREATE UNIQUE INDEX categories_pkey ON public.categories USING btree (id);

CREATE UNIQUE INDEX disciplinary_actions_pkey ON public.disciplinary_actions USING btree (id);

CREATE INDEX idx_attendance_logs_state ON public.attendance_logs USING btree (state);

CREATE UNIQUE INDEX meetings_pkey ON public.meetings USING btree (id);

CREATE UNIQUE INDEX order_items_pkey ON public.order_items USING btree (id);

CREATE UNIQUE INDEX orders_pkey ON public.orders USING btree (id);

CREATE UNIQUE INDEX products_pkey ON public.products USING btree (id);

alter table "public"."categories" add constraint "categories_pkey" PRIMARY KEY using index "categories_pkey";

alter table "public"."disciplinary_actions" add constraint "disciplinary_actions_pkey" PRIMARY KEY using index "disciplinary_actions_pkey";

alter table "public"."meetings" add constraint "meetings_pkey" PRIMARY KEY using index "meetings_pkey";

alter table "public"."order_items" add constraint "order_items_pkey" PRIMARY KEY using index "order_items_pkey";

alter table "public"."orders" add constraint "orders_pkey" PRIMARY KEY using index "orders_pkey";

alter table "public"."products" add constraint "products_pkey" PRIMARY KEY using index "products_pkey";

alter table "public"."disciplinary_actions" add constraint "disciplinary_actions_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id) not valid;

alter table "public"."disciplinary_actions" validate constraint "disciplinary_actions_created_by_fkey";

alter table "public"."disciplinary_actions" add constraint "disciplinary_actions_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) not valid;

alter table "public"."disciplinary_actions" validate constraint "disciplinary_actions_user_id_fkey";

alter table "public"."meetings" add constraint "meetings_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id) not valid;

alter table "public"."meetings" validate constraint "meetings_created_by_fkey";

alter table "public"."order_items" add constraint "order_items_order_id_fkey" FOREIGN KEY (order_id) REFERENCES public.orders(id) ON DELETE CASCADE not valid;

alter table "public"."order_items" validate constraint "order_items_order_id_fkey";

alter table "public"."order_items" add constraint "order_items_product_id_fkey" FOREIGN KEY (product_id) REFERENCES public.products(id) not valid;

alter table "public"."order_items" validate constraint "order_items_product_id_fkey";

alter table "public"."orders" add constraint "orders_status_check" CHECK ((status = ANY (ARRAY['pending'::text, 'completed'::text, 'cancelled'::text]))) not valid;

alter table "public"."orders" validate constraint "orders_status_check";

alter table "public"."products" add constraint "products_category_id_fkey" FOREIGN KEY (category_id) REFERENCES public.categories(id) not valid;

alter table "public"."products" validate constraint "products_category_id_fkey";

alter table "public"."attendance_logs" add constraint "attendance_logs_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) not valid;

alter table "public"."attendance_logs" validate constraint "attendance_logs_user_id_fkey";

alter table "public"."hr_requests" add constraint "hr_requests_type_check" CHECK ((type = ANY (ARRAY['permiso'::text, 'licencia'::text, 'novedad'::text, 'vacaciones'::text, 'incapacidad'::text, 'cambio_turno'::text]))) not valid;

alter table "public"."hr_requests" validate constraint "hr_requests_type_check";

alter table "public"."hr_requests" add constraint "hr_requests_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) not valid;

alter table "public"."hr_requests" validate constraint "hr_requests_user_id_fkey";

alter table "public"."payroll_items" add constraint "payroll_items_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) not valid;

alter table "public"."payroll_items" validate constraint "payroll_items_user_id_fkey";

alter table "public"."schedules" add constraint "schedules_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) not valid;

alter table "public"."schedules" validate constraint "schedules_user_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.is_admin()
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  RETURN EXISTS (
    SELECT 1
    FROM public.profiles
    WHERE id = auth.uid()
    AND role IN ('supervisor', 'gerente')
  );
END;
$function$
;

grant delete on table "public"."categories" to "anon";

grant insert on table "public"."categories" to "anon";

grant references on table "public"."categories" to "anon";

grant select on table "public"."categories" to "anon";

grant trigger on table "public"."categories" to "anon";

grant truncate on table "public"."categories" to "anon";

grant update on table "public"."categories" to "anon";

grant delete on table "public"."categories" to "authenticated";

grant insert on table "public"."categories" to "authenticated";

grant references on table "public"."categories" to "authenticated";

grant select on table "public"."categories" to "authenticated";

grant trigger on table "public"."categories" to "authenticated";

grant truncate on table "public"."categories" to "authenticated";

grant update on table "public"."categories" to "authenticated";

grant delete on table "public"."categories" to "service_role";

grant insert on table "public"."categories" to "service_role";

grant references on table "public"."categories" to "service_role";

grant select on table "public"."categories" to "service_role";

grant trigger on table "public"."categories" to "service_role";

grant truncate on table "public"."categories" to "service_role";

grant update on table "public"."categories" to "service_role";

grant delete on table "public"."disciplinary_actions" to "anon";

grant insert on table "public"."disciplinary_actions" to "anon";

grant references on table "public"."disciplinary_actions" to "anon";

grant select on table "public"."disciplinary_actions" to "anon";

grant trigger on table "public"."disciplinary_actions" to "anon";

grant truncate on table "public"."disciplinary_actions" to "anon";

grant update on table "public"."disciplinary_actions" to "anon";

grant delete on table "public"."disciplinary_actions" to "authenticated";

grant insert on table "public"."disciplinary_actions" to "authenticated";

grant references on table "public"."disciplinary_actions" to "authenticated";

grant select on table "public"."disciplinary_actions" to "authenticated";

grant trigger on table "public"."disciplinary_actions" to "authenticated";

grant truncate on table "public"."disciplinary_actions" to "authenticated";

grant update on table "public"."disciplinary_actions" to "authenticated";

grant delete on table "public"."disciplinary_actions" to "service_role";

grant insert on table "public"."disciplinary_actions" to "service_role";

grant references on table "public"."disciplinary_actions" to "service_role";

grant select on table "public"."disciplinary_actions" to "service_role";

grant trigger on table "public"."disciplinary_actions" to "service_role";

grant truncate on table "public"."disciplinary_actions" to "service_role";

grant update on table "public"."disciplinary_actions" to "service_role";

grant delete on table "public"."meetings" to "anon";

grant insert on table "public"."meetings" to "anon";

grant references on table "public"."meetings" to "anon";

grant select on table "public"."meetings" to "anon";

grant trigger on table "public"."meetings" to "anon";

grant truncate on table "public"."meetings" to "anon";

grant update on table "public"."meetings" to "anon";

grant delete on table "public"."meetings" to "authenticated";

grant insert on table "public"."meetings" to "authenticated";

grant references on table "public"."meetings" to "authenticated";

grant select on table "public"."meetings" to "authenticated";

grant trigger on table "public"."meetings" to "authenticated";

grant truncate on table "public"."meetings" to "authenticated";

grant update on table "public"."meetings" to "authenticated";

grant delete on table "public"."meetings" to "service_role";

grant insert on table "public"."meetings" to "service_role";

grant references on table "public"."meetings" to "service_role";

grant select on table "public"."meetings" to "service_role";

grant trigger on table "public"."meetings" to "service_role";

grant truncate on table "public"."meetings" to "service_role";

grant update on table "public"."meetings" to "service_role";

grant delete on table "public"."order_items" to "anon";

grant insert on table "public"."order_items" to "anon";

grant references on table "public"."order_items" to "anon";

grant select on table "public"."order_items" to "anon";

grant trigger on table "public"."order_items" to "anon";

grant truncate on table "public"."order_items" to "anon";

grant update on table "public"."order_items" to "anon";

grant delete on table "public"."order_items" to "authenticated";

grant insert on table "public"."order_items" to "authenticated";

grant references on table "public"."order_items" to "authenticated";

grant select on table "public"."order_items" to "authenticated";

grant trigger on table "public"."order_items" to "authenticated";

grant truncate on table "public"."order_items" to "authenticated";

grant update on table "public"."order_items" to "authenticated";

grant delete on table "public"."order_items" to "service_role";

grant insert on table "public"."order_items" to "service_role";

grant references on table "public"."order_items" to "service_role";

grant select on table "public"."order_items" to "service_role";

grant trigger on table "public"."order_items" to "service_role";

grant truncate on table "public"."order_items" to "service_role";

grant update on table "public"."order_items" to "service_role";

grant delete on table "public"."orders" to "anon";

grant insert on table "public"."orders" to "anon";

grant references on table "public"."orders" to "anon";

grant select on table "public"."orders" to "anon";

grant trigger on table "public"."orders" to "anon";

grant truncate on table "public"."orders" to "anon";

grant update on table "public"."orders" to "anon";

grant delete on table "public"."orders" to "authenticated";

grant insert on table "public"."orders" to "authenticated";

grant references on table "public"."orders" to "authenticated";

grant select on table "public"."orders" to "authenticated";

grant trigger on table "public"."orders" to "authenticated";

grant truncate on table "public"."orders" to "authenticated";

grant update on table "public"."orders" to "authenticated";

grant delete on table "public"."orders" to "service_role";

grant insert on table "public"."orders" to "service_role";

grant references on table "public"."orders" to "service_role";

grant select on table "public"."orders" to "service_role";

grant trigger on table "public"."orders" to "service_role";

grant truncate on table "public"."orders" to "service_role";

grant update on table "public"."orders" to "service_role";

grant delete on table "public"."products" to "anon";

grant insert on table "public"."products" to "anon";

grant references on table "public"."products" to "anon";

grant select on table "public"."products" to "anon";

grant trigger on table "public"."products" to "anon";

grant truncate on table "public"."products" to "anon";

grant update on table "public"."products" to "anon";

grant delete on table "public"."products" to "authenticated";

grant insert on table "public"."products" to "authenticated";

grant references on table "public"."products" to "authenticated";

grant select on table "public"."products" to "authenticated";

grant trigger on table "public"."products" to "authenticated";

grant truncate on table "public"."products" to "authenticated";

grant update on table "public"."products" to "authenticated";

grant delete on table "public"."products" to "service_role";

grant insert on table "public"."products" to "service_role";

grant references on table "public"."products" to "service_role";

grant select on table "public"."products" to "service_role";

grant trigger on table "public"."products" to "service_role";

grant truncate on table "public"."products" to "service_role";

grant update on table "public"."products" to "service_role";


  create policy "Supervisors can view all logs"
  on "public"."attendance_logs"
  as permissive
  for select
  to public
using ((EXISTS ( SELECT 1
   FROM public.profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = ANY (ARRAY['supervisor'::text, 'gerente'::text]))))));



  create policy "Users can insert own attendance_logs"
  on "public"."attendance_logs"
  as permissive
  for insert
  to public
with check ((auth.uid() = user_id));



  create policy "Users can insert own logs"
  on "public"."attendance_logs"
  as permissive
  for insert
  to public
with check ((auth.uid() = user_id));



  create policy "Users can insert their own logs"
  on "public"."attendance_logs"
  as permissive
  for insert
  to public
with check ((auth.uid() = user_id));



  create policy "Users can update own attendance_logs"
  on "public"."attendance_logs"
  as permissive
  for update
  to public
using ((auth.uid() = user_id));



  create policy "Users can view own logs"
  on "public"."attendance_logs"
  as permissive
  for select
  to public
using ((auth.uid() = user_id));



  create policy "Users can view their own logs"
  on "public"."attendance_logs"
  as permissive
  for select
  to public
using ((auth.uid() = user_id));



  create policy "Public read categories"
  on "public"."categories"
  as permissive
  for select
  to public
using (true);



  create policy "Supervisors manage discipline"
  on "public"."disciplinary_actions"
  as permissive
  for all
  to public
using ((EXISTS ( SELECT 1
   FROM public.profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = ANY (ARRAY['supervisor'::text, 'gerente'::text]))))));



  create policy "Users view own discipline"
  on "public"."disciplinary_actions"
  as permissive
  for select
  to public
using ((auth.uid() = user_id));



  create policy "Public insert items"
  on "public"."order_items"
  as permissive
  for insert
  to public
with check (true);



  create policy "Public insert orders"
  on "public"."orders"
  as permissive
  for insert
  to public
with check (true);



  create policy "Public read products"
  on "public"."products"
  as permissive
  for select
  to public
using (true);



  create policy "Users can update their own profile"
  on "public"."profiles"
  as permissive
  for update
  to public
using ((auth.uid() = id));



  create policy "Users can view their own profile"
  on "public"."profiles"
  as permissive
  for select
  to public
using ((auth.uid() = id));



  create policy "Management manage schedules"
  on "public"."schedules"
  as permissive
  for all
  to public
using (public.is_admin());



  create policy "Users view own schedule"
  on "public"."schedules"
  as permissive
  for select
  to public
using ((auth.uid() = user_id));



  create policy "Admins view all attachments"
  on "storage"."objects"
  as permissive
  for select
  to authenticated
using ((bucket_id = 'hr-attachments'::text));



  create policy "Authenticated users can upload files"
  on "storage"."objects"
  as permissive
  for insert
  to authenticated
with check ((bucket_id = 'hr-attachments'::text));



  create policy "Authenticated users can view files"
  on "storage"."objects"
  as permissive
  for select
  to authenticated
using ((bucket_id = 'hr-attachments'::text));



  create policy "Authenticated users view own files"
  on "storage"."objects"
  as permissive
  for select
  to authenticated
using ((bucket_id = 'hr-attachments'::text));



  create policy "INSERT apu99p_0"
  on "storage"."objects"
  as permissive
  for insert
  to authenticated
with check ((bucket_id = 'hr-attachments'::text));



  create policy "Permitir todo apu99p_0"
  on "storage"."objects"
  as permissive
  for select
  to authenticated
using ((bucket_id = 'hr-attachments'::text));



  create policy "Permitir todo apu99p_1"
  on "storage"."objects"
  as permissive
  for insert
  to authenticated
with check ((bucket_id = 'hr-attachments'::text));



  create policy "Permitir todo apu99p_2"
  on "storage"."objects"
  as permissive
  for update
  to authenticated
using ((bucket_id = 'hr-attachments'::text));



  create policy "SELECT apu99p_0"
  on "storage"."objects"
  as permissive
  for select
  to authenticated
using ((bucket_id = 'hr-attachments'::text));


DO $$
BEGIN
  IF to_regclass('storage.objects') IS NOT NULL THEN
    EXECUTE 'DROP TRIGGER IF EXISTS objects_delete_delete_prefix ON storage.objects';
    EXECUTE 'DROP TRIGGER IF EXISTS objects_insert_create_prefix ON storage.objects';
    EXECUTE 'DROP TRIGGER IF EXISTS objects_update_create_prefix ON storage.objects';
  END IF;

  IF to_regclass('storage.prefixes') IS NOT NULL THEN
    EXECUTE 'DROP TRIGGER IF EXISTS prefixes_create_hierarchy ON storage.prefixes';
    EXECUTE 'DROP TRIGGER IF EXISTS prefixes_delete_hierarchy ON storage.prefixes';
  END IF;
END $$;

DO $$
BEGIN
  IF to_regclass('storage.objects') IS NOT NULL AND EXISTS (
    SELECT 1
    FROM pg_proc p
    JOIN pg_namespace n ON n.oid = p.pronamespace
    WHERE n.nspname = 'storage'
      AND p.proname = 'delete_prefix_hierarchy_trigger'
  ) THEN
    CREATE TRIGGER objects_delete_delete_prefix AFTER DELETE ON storage.objects
    FOR EACH ROW EXECUTE FUNCTION storage.delete_prefix_hierarchy_trigger();
  END IF;
END $$;

DO $$
BEGIN
  IF to_regclass('storage.prefixes') IS NOT NULL AND EXISTS (
    SELECT 1
    FROM pg_proc p
    JOIN pg_namespace n ON n.oid = p.pronamespace
    WHERE n.nspname = 'storage'
      AND p.proname = 'delete_prefix_hierarchy_trigger'
  ) THEN
    CREATE TRIGGER prefixes_delete_hierarchy AFTER DELETE ON storage.prefixes
    FOR EACH ROW EXECUTE FUNCTION storage.delete_prefix_hierarchy_trigger();
  END IF;
END $$;

DO $$
BEGIN
  IF to_regclass('storage.objects') IS NOT NULL AND EXISTS (
    SELECT 1
    FROM pg_proc p
    JOIN pg_namespace n ON n.oid = p.pronamespace
    WHERE n.nspname = 'storage'
      AND p.proname = 'objects_insert_prefix_trigger'
  ) THEN
    CREATE TRIGGER objects_insert_create_prefix BEFORE INSERT ON storage.objects
    FOR EACH ROW EXECUTE FUNCTION storage.objects_insert_prefix_trigger();
  END IF;
END $$;

DO $$
BEGIN
  IF to_regclass('storage.objects') IS NOT NULL AND EXISTS (
    SELECT 1
    FROM pg_proc p
    JOIN pg_namespace n ON n.oid = p.pronamespace
    WHERE n.nspname = 'storage'
      AND p.proname = 'objects_update_prefix_trigger'
  ) THEN
    CREATE TRIGGER objects_update_create_prefix BEFORE UPDATE ON storage.objects
    FOR EACH ROW
    WHEN (((new.name <> old.name) OR (new.bucket_id <> old.bucket_id)))
    EXECUTE FUNCTION storage.objects_update_prefix_trigger();
  END IF;
END $$;

DO $$
BEGIN
  IF to_regclass('storage.prefixes') IS NOT NULL AND EXISTS (
    SELECT 1
    FROM pg_proc p
    JOIN pg_namespace n ON n.oid = p.pronamespace
    WHERE n.nspname = 'storage'
      AND p.proname = 'prefixes_insert_trigger'
  ) THEN
    CREATE TRIGGER prefixes_create_hierarchy BEFORE INSERT ON storage.prefixes
    FOR EACH ROW WHEN ((pg_trigger_depth() < 1))
    EXECUTE FUNCTION storage.prefixes_insert_trigger();
  END IF;
END $$;
